# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlpanode/dlpanode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlpanode/dlpanode.proto',
  package='dlpanode',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x64lpanode/dlpanode.proto\x12\x08\x64lpanode\"\x18\n\x06Matrix\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x0c\n\nNoResponse2I\n\nDLPAClient\x12;\n\x0f\x45ncryptNoisySum\x12\x10.dlpanode.Matrix\x1a\x14.dlpanode.NoResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='dlpanode.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='dlpanode.Matrix.values', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=61,
)


_NORESPONSE = _descriptor.Descriptor(
  name='NoResponse',
  full_name='dlpanode.NoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['NoResponse'] = _NORESPONSE

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), dict(
  DESCRIPTOR = _MATRIX,
  __module__ = 'dlpanode.dlpanode_pb2'
  # @@protoc_insertion_point(class_scope:dlpanode.Matrix)
  ))
_sym_db.RegisterMessage(Matrix)

NoResponse = _reflection.GeneratedProtocolMessageType('NoResponse', (_message.Message,), dict(
  DESCRIPTOR = _NORESPONSE,
  __module__ = 'dlpanode.dlpanode_pb2'
  # @@protoc_insertion_point(class_scope:dlpanode.NoResponse)
  ))
_sym_db.RegisterMessage(NoResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class DLPAClientStub(object):
    """DLPAClient defines a servcie of the distributed Laplace Perturbation
    Algorithm (DLPA) client.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.EncryptNoisySum = channel.unary_unary(
          '/dlpanode.DLPAClient/EncryptNoisySum',
          request_serializer=Matrix.SerializeToString,
          response_deserializer=NoResponse.FromString,
          )


  class DLPAClientServicer(object):
    """DLPAClient defines a servcie of the distributed Laplace Perturbation
    Algorithm (DLPA) client.
    """

    def EncryptNoisySum(self, request, context):
      """EncryptNoisySum is the method to send a matrix using Encrypt-Noisy-Sum
      protocol.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DLPAClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'EncryptNoisySum': grpc.unary_unary_rpc_method_handler(
            servicer.EncryptNoisySum,
            request_deserializer=Matrix.FromString,
            response_serializer=NoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'dlpanode.DLPAClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDLPAClientServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """DLPAClient defines a servcie of the distributed Laplace Perturbation
    Algorithm (DLPA) client.
    """
    def EncryptNoisySum(self, request, context):
      """EncryptNoisySum is the method to send a matrix using Encrypt-Noisy-Sum
      protocol.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDLPAClientStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """DLPAClient defines a servcie of the distributed Laplace Perturbation
    Algorithm (DLPA) client.
    """
    def EncryptNoisySum(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """EncryptNoisySum is the method to send a matrix using Encrypt-Noisy-Sum
      protocol.
      """
      raise NotImplementedError()
    EncryptNoisySum.future = None


  def beta_create_DLPAClient_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('dlpanode.DLPAClient', 'EncryptNoisySum'): Matrix.FromString,
    }
    response_serializers = {
      ('dlpanode.DLPAClient', 'EncryptNoisySum'): NoResponse.SerializeToString,
    }
    method_implementations = {
      ('dlpanode.DLPAClient', 'EncryptNoisySum'): face_utilities.unary_unary_inline(servicer.EncryptNoisySum),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_DLPAClient_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('dlpanode.DLPAClient', 'EncryptNoisySum'): Matrix.SerializeToString,
    }
    response_deserializers = {
      ('dlpanode.DLPAClient', 'EncryptNoisySum'): NoResponse.FromString,
    }
    cardinalities = {
      'EncryptNoisySum': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'dlpanode.DLPAClient', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
